#%RAML 1.0
title: file-upload-frontend
protocols: [ HTTP, HTTPS ]
baseUri: https://{environmentHost}/file-upload
baseUriParameters:
  environmentHost:
    enum: ["www-dev.tax.service.gov.uk","www-qa.tax.service.gov.uk"]
description: Upload files to the Tax Platform

/envelope:
  post:
    description: Create an envelope
    body:
      application/json:
        example: {}
    responses:
      201:
        description: Successfully created
        headers:
          Location:
            description: URI for the resource for showing this envelope
            example: www-dev.tax.service.gov.uk/file-upload/envelope/1234567890

  /{envelopeId}:
    uriParameters:
      envelopeId:
        displayName: Envelope ID
        example: "4e0bf8f1-d0b3-4892-94b4-f2a03ecf70fa"
    get:
      description: Check the existence of an Envelope
      responses:
        200:
          description: Envelope exists
          body:
            application/json:
              example: { "id": "4e0bf8f1-d0b3-4892-94b4-f2a03ecf70fa" }
        404:
          description: Envelope with specified ID not found
          body:
            application/json:
              example: |
                {
                  "error": {
                    "msg": "Envelope 4e0bf8f1-d0b3-4892-94b4-f2a03ecf70fa not found"
                  }
                }
  delete:
    description: Deletion of an Envelope
    responses:
      202:
        description: Successful
      404:
        description: Envelope not found
        body:
          application/json:
            example: |
              {
                "error": {
                "msg": "Envelope 4e0bf8f1-d0b3-4892-94b4-f2a03ecf70fa not found"
                }
              }
