#%RAML 1.0
title: file-upload-frontend
protocols: [ HTTP, HTTPS ]
baseUri: https://{environmentHost}/file-upload
baseUriParameters:
  environmentHost:
    enum: ["www-dev.tax.service.gov.uk","www-qa.tax.service.gov.uk"]
description: Upload files to the Tax Platform

/envelope:
  post:
    description: Create an envelope
    body:
      application/json:
        example: {}
    responses:
      201:
        description: Successfully created
        headers:
          Location:
            description: URI for the resource for showing this envelope
            example: www-dev.tax.service.gov.uk/file-upload/envelope/1234567890

  /{envelopeId}:
    uriParameters:
      envelopeId:
        displayName: Envelope ID
        example: "4e0bf8f1-d0b3-4892-94b4-f2a03ecf70fa"
    get:
      description: Check the existence of an Envelope
      responses:
        200:
          description: Envelope exists
          body:
            application/json:
              example: { "id": "4e0bf8f1-d0b3-4892-94b4-f2a03ecf70fa" }
        404:
          description: Envelope with specified ID not found
          body:
            application/json:
              example: |
                {
                  "error": {
                    "msg": "Envelope 4e0bf8f1-d0b3-4892-94b4-f2a03ecf70fa not found"
                  }
                }
    delete:
      description: Deletion of an Envelope
      responses:
        202:
          description: Deleted
        404:
          description: Envelope not found
          body:
            application/json:
              example: |
                {
                  "error": {
                  "msg": "Envelope 4e0bf8f1-d0b3-4892-94b4-f2a03ecf70fa not found"
                  }
                }
    /file/{fileId}:
      uriParameters:
        fileId:
          displayName: File ID
          example: "1234567890"
      /content:
        put:
          description: Upload a file to an envelope
          responses:
            200:
              description: Uploaded
            404:
              description: Envelope not found
              body:
                application/json:
                  example: |
                    {
                      "error": {
                      "msg": "Envelope 4e0bf8f1-d0b3-4892-94b4-f2a03ecf70fa not found"
                      }
                    }
        get:
          description: Get a files contents
          responses:
            200:
              description: The files body
            404:
              description: File not found
              body:
                application/json:
                  example: |
                    {
                      "error": {
                      "msg": "File 123456789 not found in envelope: sss123456-03d6-4ae3-b8c6-3b5c6ad2f748"
                      }
                    }
      /metadata:
        put:
          description: Upload file metadata
          body:
            application/json:
              example: |
                {
                  "name":"test.jpg",
                  "contentType":"application/pdf",
                  "metadata":{
                    "id":"1234567890",
                    "origin":{
                      "nino":"AB123456Z",
                      "token":"48729348729348732894",
                      "session":"cd30f8ec-d866-4ae0-82a0-1bc720f1cb09",
                      "agent":"292929292",
                      "trustedHelper":"8984293480239480",
                      "ipAddress":"1.2.3.4"
                    },
                    "sender":{
                      "service":"some-service-identifier/v1.2.33"
                    }
                  }
                }
          responses:
            200:
              description: Metadata uploaded
            404:
              description: File not found
              body:
                application/json:
                  example: |
                    {
                      "error": {
                      "msg": "File 123456789 not found in envelope: sss123456-03d6-4ae3-b8c6-3b5c6ad2f748"
                      }
                    }
        get:
          description: Upload file metadata
          body:
            application/json:
              example: |
                {
                  "name":"test.jpg",
                  "contentType":"application/pdf",
                  "metadata":{
                    "id":"1234567890",
                    "origin":{
                      "nino":"AB123456Z",
                      "token":"48729348729348732894",
                      "session":"cd30f8ec-d866-4ae0-82a0-1bc720f1cb09",
                      "agent":"292929292",
                      "trustedHelper":"8984293480239480",
                      "ipAddress":"1.2.3.4"
                    },
                    "sender":{
                      "service":"some-service-identifier/v1.2.33"
                    }
                  }
                }
          responses:
            200:
              description: The files metadata
              body:
                application/json:
                  example: |
                    {
                      "id" : "fileId-b690e15e-87cc-47bb-af9c-58c2482f11c4",
                      "name" : "test.jpg",
                      "contentType" : "application/pdf",
                      "metadata" : {
                        "id" : "1234567890",
                        "origin" : {
                          "nino" : "AB123456Z",
                          "token" : "48729348729348732894",
                          "session" : "cd30f8ec-d866-4ae0-82a0-1bc720f1cb09",
                          "agent" : "292929292",
                          "trustedHelper" : "8984293480239480",
                          "ipAddress" : "1.2.3.4"
                        },
                        "sender" : {
                          "service" : "some-service-identifier/v1.2.33"
                        }
                      },
                      "href" : "/file-upload/envelope/d16ea92c-2345-4552-a6b8-f80144671352/file/fileId-b690e15e-87cc-47bb-af9c-58c2482f11c4/content"
                    }
            404:
              description: File not found
              body:
                application/json:
                  example: |
                    {
                      "error": {
                      "msg": "File 123456789 not found in envelope: sss123456-03d6-4ae3-b8c6-3b5c6ad2f748"
                      }
                    }
  /events/{eventType}:
    uriParameters:
      eventType:
        displayName: Event ID
        enum: ["novirusdetected","quarantined","totransientmoved","movingtotransientfailed","virusdetected"]
    post:
